### PR TITLE
ScopedCSSRules[] on css function

### PR DESCRIPTION
**Pull request by etc-tiago**
As mentioned in issue #28:

- This change will allow accept ScopedCSSRules and ScopedCSSRules[] on `css` function. E.g.:

```ts
css({ margin: 0 })

// or

const btnBase: ScopedCSSRules  = ({ margin: 0, padding: 10, color: '#0088cc' })
css([btnBase, { padding: 0 }])

// { margin: 0, padding: 0, color: '#0088cc' }
```

- This change also avoids the use of `!import`, since there will not be 2 styles with the same property.

- And last but not least, this change does not break the current use of the `css` function

### CODE REVIEW

**Comment by kripod** [comment]
Thanks for the submission! I would be curious to see how this differs from using object spreading on the parameter of `css`. A discussion about composability has been going on in #3. Please join the conversation over there! 🤗

**Comment by etc-tiago** [comment]
> I would be curious to see how this differs from using object spreading on the parameter of `css`.

It doesn't really differ, only Object.assign is backwards compatible and used with javascript without babel / typescript. I have some customers who still support iOS 10, so sometimes it's just more convenient to choose Object.assign.

But I fully understand the option of not adding Object.assign, even refusing to add ScopedCSSRules[] to otion, since iOS 11 onwards already has compatibility with object spreading and we cannot stick to past systems.

**Comment by etc-tiago** [comment]
But I would like to have access to ScopedCSSRules to type css classes, so I would like to close this pull request and open a new one to export ScopedCSSRules.

Let me know your opinion so that I can move forward with the new pull request.

**Comment by kripod** [comment]
Sounds reasonable, thank you! 😊

**Pull request closed without merging**
